### PR TITLE
bugfix: branch checking logic

### PR DESCRIPTION
**Pull request by sdebruyn**
I'm sorry for the inconvenience, but I missed this while adding the production/development features.

_PS: how do you recommend testing wercker steps? For now, I just create some environment variables and then run `run.sh` on my hugo code._

### CODE REVIEW

**Comment by ArjenSchwarz** [comment]
@SamuelDebruyn I test it the same way actually. Spin up a docker container, set everything and try it that way. I haven't really managed to find a way that I'm happy with. I have some spare time coming up and might try to find something better then. If I do, I'll let you know about it.
Either way, thanks for supplying the fix.

**Comment by sdebruyn** [comment]
Thanks!

It still seems to have picked the wrong build flags, so there's still something I'm not seeing...  Or you might need to bump the version to 1.6.1 so that wercker uses the new version. https://app.wercker.com/#buildstep/55eea17321e291701600242a

**Comment by ArjenSchwarz** [comment]
I've bumped the version number to 1.6.1, can you check if it's working well for you now?

**Comment by sdebruyn** [comment]
That did it, it's working fine now! :)

**Pull request merged**
